### ISSUE TITLE
Support for clang 3.1

### ISSUE THREAD

**Issue by root42** [brianjcj/auto-complete-clang#11]
I think there are some problems with clang 3.1. When using clang 3.0, completion works mostly fine on my setup, using Emacs 23.2.1. But when I switch to clang 3.1, only few completions are found, mostly types. Variables are not shown at all. Is this a known problem? Is it easy to fix?

**Comment by brianjcj** [comment]
I am using clang 3.1 and it woks just fine:

brianjcjMacBook-Pro:src brianjcj$ clang -v
Apple clang version 3.1 (tags/Apple/clang-318.0.54) (based on LLVM 3.1svn)
Target: x86_64-apple-darwin11.4.0
Thread model: posix

Could you provide some examples of the problems you met?

**Comment by root42** [comment]
I think this was a hiccup. On my Mac this also works. At work under Linux I experienced this problem, but I think I made some mistake, so that clang couldn't complete. So I'll close this issue. Thanks.
