### ISSUE TITLE
Don't understand myoptdir variable

### ISSUE THREAD

**Issue by csfreebird** [brianjcj/auto-complete-clang#2]
Hello,
  I read the article from here:
http://felipetonello.com/blog/2011/06/07/awesome-c-cpp-auto-completion-in-emacs/
 And jumped to your site.
 https://github.com/brianjcj/auto-complete-clang#readme

I tried your configuration on github.com,but got the following error message:
Warning (initialization): An error occurred while loading `/home/chenshu/.emacs':
Symbol's value as variable is void: myoptdir

I don't know what myoptdir variable is for?

**Comment by brianjcj** [comment]
It is defined in my own .emacs, It is only used in here:

(add-to-list 'load-path (concat myoptdir "AC"))
(require 'auto-complete-config)
(add-to-list 'ac-dictionary-directories (concat myoptdir "AC/ac-dict"))

You can just replace it with the dir string where your AutoComplete plugin installed.
e.g., if your install AC in dir /home/chenshu/foo/bar/AC, then you can change it to:

(add-to-list 'load-path "/home/chenshu/foo/bar/AC")
(require 'auto-complete-config)
(add-to-list 'ac-dictionary-directories "/home/chenshu/foo/bar/AC/ac-dict")

**Comment by csfreebird** [comment]
Thanks.I changed it,it worked,no error. But I can't see the correct member functions listed by auto-complete-clang.
I set my header like so:
(defun my-ac-config ()
  (setq ac-clang-flags (split-string "-I/usr/include/c++/4.5"))  //only add this line
  (setq-default ac-sources '(ac-source-abbrev ac-source-dictionary ac-source-words-in-same-mode-buffers))

my test c++ application only has one main.cpp file.
#include <string>
using namespace std;

int main()
{
    printf("Hello World2 from Main!\n");
    string str;
    str.
    return 0;
}

The string class(basic_string<char>)'s member functions are not listed,but some global functions are listed,e.g.
_Tp const& min(_Tp const &__a, _Tp const &__b)

Any idea?

**Comment by csfreebird** [comment]
sudo ln -s /usr/include/c++/4.5/`uname -m`-linux-gnu/bits/\* /usr/include/c++/4.5/bits
I found the above command from your article.Thanks,it works.

**Comment by brianjcj** [comment]
Good！
