### ISSUE TITLE
How to configure to automatically trigger completion by ".", "::", and "->"

### ISSUE THREAD

**Issue by oracleyue** [brianjcj/auto-complete-clang#31]
I saw you have defined these symbols as `ac-clang-prefix`, however, under my setting, they don't automatically trigger any completion. When I read your source code, you don't offer such a functionality, am I right? Do you know any easy way to make this function?  I saw a solution using `ac-omni-completion-sources`, unfortunately it has been deprecated. Any ideas? (Maybe I should read source codes of auto-complete.) Many thanks!

**Comment by articuluxe** [comment]
Was there any resolution?
