### ISSUE TITLE
clang 2.9 or 3.0?

### ISSUE THREAD

**Issue by vasconde** [brianjcj/auto-complete-clang#4]
Hi. To use auto-complet-clang, what is the version of clang that I should use?

Because in my case it works with clang 2.9 (on lubuntu 11.10)
and it doesn't with clang 3.0 (on openSUSE 12.1)

**Comment by brianjcj** [comment]
rather busy recently. I will take a look at clang 3.0 this weekend. thanks.

**Comment by brianjcj** [comment]
I tried clang-3.0. The code complete function always failed to
recognize the standard include files such as "string". I used the -v
option and then found the clang's inlcude search list is empty.

Here is the solution:
1. find out the include file search pathes of your g++:

echo "" | g++ -v -x c++ -E -

you wil get something like this:

#include "..." search starts here：
#include <...> search starts here：
 /usr/include/c++/4.6
 /usr/include/c++/4.6/x86_64-linux-gnu/.
 /usr/include/c++/4.6/backward
 /usr/lib/gcc/x86_64-linux-gnu/4.6.1/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/4.6.1/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
1. setting the ac-clang-flags to include these default include pathes:
   e.g.,

(setq ac-clang-flags
      (mapcar (lambda (item)(concat "-I" item))
              (split-string
               "
 /usr/include/c++/4.6
 /usr/include/c++/4.6/x86_64-linux-gnu/.
 /usr/include/c++/4.6/backward
 /usr/lib/gcc/x86_64-linux-gnu/4.6.1/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/4.6.1/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
"
               )))

You can put it into your .emacs file.

Then code completion works just fine!

**Comment by vasconde** [comment]
Nice, tks ;)
