### ISSUE TITLE
causes emacs 24 crashed

### ISSUE THREAD

**Issue by ghost** [brianjcj/auto-complete-clang#6]
I'm using in Emacs24 on CentOS6 with llvm 3.0 built by myself.
Emacs 24 crashes sometimes. I cannot determine, but the clang-compile-failure (as fellow) is NOT the determined reason.
"
_clang error_
<stdin>:2:10: fatal error: 'EventHandler.hpp' file not found
# include "EventHandler.hpp"

"

**Comment by ghost** [comment]
BTW, it's an awesome tool! Thanks!

**Comment by brianjcj** [comment]
Not sure about the problem. Maybe there is somthing wrong in the clang config....
