### ISSUE TITLE
Wrong parameters for pthread_create

### ISSUE THREAD

**Issue by weimzh** [brianjcj/auto-complete-clang#8]
Steps to reproduce:

1) #include <pthread.h> in a .c file
2) type "pthread_create" and press C-tab
3) check for the parameters for the pthread_create function in the completion menu
4) press enter
5) check for the parameters appeared in the buffer

What happened:
the parameters in the buffer were wrong

Excepted result:
the parameters appeared in the buffer should be the same as the one appeared in the completion menu

Screenshots:
http://redwings.tk/sites/default/files/1.JPG
http://redwings.tk/sites/default/files/2.JPG

**Comment by weimzh** [comment]
it seems auto-complete-clang simply does not like function pointers:
http://redwings.tk/sites/default/files/acclang-func-ptr.JPG

**Comment by weimzh** [comment]
fixed. patch:
http://redwings.tk/sites/default/files/auto-complete-clang.diff

there are still some issues with parameters though (which needs to be solved before commiting), however at least it's usable. I don't have a good understanding on Lisp so I can't solve it and not sure if this will cause other problems.

**Comment by brianjcj** [comment]
Fixed. Thanks for reporting the problem. Any further problems, pls let me know.

**Comment by weimzh** [comment]
Cool & looks much more professional than my simple hack ;)
Thanks.

**Comment by weimzh** [comment]
sorry, but there is still one more issue (which was why I replaced out all "(*)" in the patch IIRC):
http://i.6.cn/cvbnm/15/c6/44/effc8ea7f979e41ffd9c3f9203d0c58e.jpg

**Comment by brianjcj** [comment]
fixed. I made some special handling for function ptr, and changed some implementation details. try again please.

**Comment by weimzh** [comment]
all works now. Thanks very much ;)
