### ISSUE TITLE
Not work with yasnippet

### ISSUE THREAD

**Issue by DYFeng** [brianjcj/auto-complete-clang#9]
here is my .emacs

'''lisp
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;yasnippet
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(require 'yasnippet)
(yas/initialize)
(setq yas/snippet-dirs '("~/.emacs.d/el-get/yasnippet/snippets" "~/.emacs.d/el-get/yasnippet/extras/imported"))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;auto-complete
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(require 'pos-tip)  
(require 'auto-complete)  
(require 'auto-complete-config)  
(ac-config-default)
(global-auto-complete-mode t)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;auto-complete-clang
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(require 'auto-complete-clang)
(defun ac-cc-mode-setup ()  
  (make-local-variable 'ac-auto-start)  
  (setq ac-auto-start nil)              ;auto complete using clang is CPU sensitive  
  (setq ac-sources (append '(ac-source-clang ac-source-yasnippet) ac-sources)))

(setq ac-sources (append '(ac-source-abbrev ac-source-dictionary ac-source-words-in-same-mode-buffers) ac-sources))
(setq ac-clang-flags (list 
              "/usr/include/c++/4.6"
              "/usr/include/c++/4.6/x86_64-linux-gnu/."
              "/usr/include/c++/4.6/backward"
              "/usr/lib/gcc/x86_64-linux-gnu/4.6/include"
              "/usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed"
              "/usr/include/x86_64-linux-gnu"
              "/usr/include"
              "/usr/local/include"
              ))
(add-hook 'c-mode-common-hook 'ac-cc-mode-setup)  
(add-hook 'css-mode-hook 'ac-css-mode-setup)
(add-hook 'emacs-lisp-mode-hook 'ac-emacs-lisp-mode-setup)

(define-key c-mode-base-map (kbd "TAB") 'auto-complete)
'''

When I do the complete
# inc<TAB>

I get the error message

Return a list of `yas/table' objects. The list of modes to
consider is returned by`yas/modes-to-activate'" (remove nil (mapcar (function (lambda (mode-name) (gethash mode-name yas/tables))) (yas/modes-to-activate)))), 1
Auto-saving...

But It's good at complete 
for<TAB> etc...

**Comment by brianjcj** [comment]
It seems a yasnippet config problem, and not relevant to auto-complete-clang. What versions of yasnippet and auto-complete are you using?
And pls try to narrow down the problem by testing the following cases and see whether the problem still happens:
1. use yasnippet only (not load/activate auto-complete and auto-complete-clang)
2. use yasnippet and auto-complete only (not load/activate auto-complete-clang.
3. use the configuration as the README of auto-complete-clang suggests.

**Comment by DYFeng** [comment]
Hmm,I don't know why it works now....However,it works

**Comment by qingw** [comment]
I have the same question to auto complete haskell mode
